[package]
name = "Encypor-X-Decryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
chacha20poly1305 = "0.10.1"
cipher = "0.4.4"
ctr = "0.9.2"
dirs = "5.0.1"
hex = "0.4.3"
winapi = {version = "0.3.9", features = ["winuser"]}
